# fly.toml app configuration file generated for buza on 2025-12-03T15:45:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'buza'
primary_region = 'lhr'

[build]
dockerfile = "Dockerfile"
[env]
PORT = "5678"

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[mounts]
  source = "n8n_data"
  destination = "/home/node/.n8n"


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
